use_frameworks!

target 'CJDataBase_Example' do
  pod 'CJDataBase', :path => '../'

  target 'CJDataBase_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
