use_frameworks!

target 'CJDataBase_Example' do
  pod 'CJDataBase', :path => '../'

  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['SWIFT_VERSION'] = '3.0'
  #     end
  #   end
  # end
end
